---
abstract: 'Perl extension for extract address from CEP (zip code) number'
author:
  - 'Renato CRON <rentocron@cpan.org>'
build_requires:
  Carp: 0
  Data::Dumper: 0
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Correios-CEP
requires:
  Encode: 0
  HTML::TreeBuilder::XPath: 0
  LWP::UserAgent: 0
  strict: 0
  utf8: 0
resources:
  bugtracker: http://github.com/renatocron/WWW--Correios--CEP/issues
  repository: http://renatocron@github.com/renatocron/WWW--Correios--CEP.git
version: 0.03
